### PR TITLE
bump default cis benchmark version to cis-1.23

### PR DESCRIPTION
**Pull request by addyess**
Dependent on merge of:
* https://github.com/charmed-kubernetes/kube-bench-config/pull/5

### CODE REVIEW

**Comment by addyess** [comment]
locally built etcd with this change:
```bash
❯ juju run-action --wait etcd/0 cis-benchmark                  
unit-etcd-0:
  UnitId: etcd/0
  id: "42"
  results:
    cmd: /home/ubuntu/kube-bench/kube-bench -D /home/ubuntu/kube-bench/cfg-ck --benchmark
      cis-1.23 --noremediations --noresults run --targets etcd
    report: juju scp etcd/0:/home/ubuntu/kube-bench-results/results-text-lt6ey6h2
      .
    summary: |+
      == Summary etcd ==
      7 checks PASS
      0 checks FAIL
      0 checks WARN
      0 checks INFO

      == Summary total ==
      7 checks PASS
      0 checks FAIL
      0 checks WARN
      0 checks INFO

  status: completed
  timing:
    completed: 2022-04-26 21:37:49 +0000 UTC
    enqueued: 2022-04-26 21:37:47 +0000 UTC
    started: 2022-04-26 21:37:48 +0000 UTC
```

**Comment by addyess** [comment]
locally built kubernetes-worker with this change:

```bash
❯ juju run-action --wait kubernetes-worker/4 cis-benchmark
unit-kubernetes-worker-4:
  UnitId: kubernetes-worker/4
  id: "55"
  results:
    cmd: /home/ubuntu/kube-bench/kube-bench -D /home/ubuntu/kube-bench/cfg-ck --benchmark
      cis-1.23 --noremediations --noresults run --targets node
    report: juju scp kubernetes-worker/4:/home/ubuntu/kube-bench-results/results-text-cj602dsq
      .
    summary: |+
      == Summary node ==
      21 checks PASS
      0 checks FAIL
      2 checks WARN
      0 checks INFO

      == Summary total ==
      21 checks PASS
      0 checks FAIL
      2 checks WARN
      0 checks INFO

  status: completed
  timing:
    completed: 2022-04-27 14:00:27 +0000 UTC
    enqueued: 2022-04-27 14:00:19 +0000 UTC
    started: 2022-04-27 14:00:21 +0000 UTC
```

**Comment by addyess** [comment]
locally built kubernetes-control-plane with this change:  (was run on a upgraded `kubernetes-master` application)

```bash
❯ juju run-action --wait kubernetes-master/0 cis-benchmark
unit-kubernetes-master-0:
  UnitId: kubernetes-master/0
  id: "57"
  results:
    cmd: /home/ubuntu/kube-bench/kube-bench -D /home/ubuntu/kube-bench/cfg-ck --benchmark
      cis-1.23 --noremediations --noresults run --targets master
    report: juju scp kubernetes-master/0:/home/ubuntu/kube-bench-results/results-text-0sq8cgmt
      .
    summary: |+
      == Summary master ==
      48 checks PASS
      0 checks FAIL
      6 checks WARN
      8 checks INFO

      == Summary total ==
      48 checks PASS
      0 checks FAIL
      6 checks WARN
      8 checks INFO

  status: completed
  timing:
    completed: 2022-04-27 14:03:33 +0000 UTC
    enqueued: 2022-04-27 14:01:06 +0000 UTC
    started: 2022-04-27 14:03:30 +0000 UTC
```

**Review by kwmonroe — APPROVED** [review]
wow, thanks for addressing inclusive bits and up'ing k8s charms as needed. +1.

**Pull request merged**
